// <auto-generated />
using MyMusic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyMusic.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyMusic.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Name = "K-POP"
                        },
                        new
                        {
                            CategoryID = 2,
                            Name = "R&B"
                        },
                        new
                        {
                            CategoryID = 3,
                            Name = "Instrumental"
                        });
                });

            modelBuilder.Entity("MyMusic.Models.Song", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Artist")
                       .IsRequired();

                    b.HasKey("SongID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongID = 1,
                            CategoryID = 1,
                            Name = "Life Goes On",
                            Artist = "BTS"
                        },
                        new
                        {
                            SongID = 2,
                            CategoryID = 1,
                            Name = "Wonderland",
                            Artist = "ATEEZ"
                        },
                        new
                        {
                            SongID = 3,
                            CategoryID = 1,
                            Name = "Spring Day",
                            Artist = "BTS"
                        },
                        new
                        {
                            SongID = 4,
                            CategoryID = 1,
                            Name = "New Rules",
                            Artist = "TOMORROW X TOGETHER"
                        },
                        new
                        {
                            SongID = 5,
                            CategoryID = 1,
                            Name = "Alcohol-Free",
                            Artist = "TWICE"
                        },
                        new
                        {
                            SongID = 6,
                            CategoryID = 1,
                            Name = "Middle of the Night",
                            Artist = "MONSTA X"
                        },
                        new
                        {
                            SongID = 7,
                            CategoryID = 2,
                            Name = "Woman",
                            Artist = "Doja Cat"
                        },
                        new
                        {
                            SongID = 8,
                            CategoryID = 2,
                            Name = "End of the Road",
                            Artist = "Boyz II Men"
                        },
                        new
                        {
                            SongID = 9,
                            CategoryID = 3,
                            Name = "Seul Ce Soir",
                            Artist = "Swing 41"
                        },
                        new
                        {
                            SongID = 10,
                            CategoryID = 3,
                            Name = "Cake Waltz (Jimin Theme)",
                            Artist = "BTS"
                        });
                });

            modelBuilder.Entity("MyMusic.Models.Song", b =>
                {
                    b.HasOne("MyMusic.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
